---
# Handler for rabbitmq notifications

- name: restart firewalld
  service: 
    name: firewalld 
    state: restarted
- name: restart rabbitmq
  service: 
    name: rabbitmq-server 
    stat: restarted
